// <auto-generated />
using System;
using AngleSharp.Dom;

namespace AngleSharp.Html.Parser.Utf8;

internal static partial class Utf8CanonicalNameProvider
{
    public static Boolean TryGetHtmlTag(ReadOnlySpan<Byte> name, out String canonical)
    {
        canonical = name.Length switch
        {
            1 => LookupHtmlTagLength1(name),
            2 => LookupHtmlTagLength2(name),
            3 => LookupHtmlTagLength3(name),
            4 => LookupHtmlTagLength4(name),
            5 => LookupHtmlTagLength5(name),
            6 => LookupHtmlTagLength6(name),
            7 => LookupHtmlTagLength7(name),
            8 => LookupHtmlTagLength8(name),
            9 => LookupHtmlTagLength9(name),
            10 => LookupHtmlTagLength10(name),
            15 => LookupHtmlTagLength15(name),
            _ => null!,
        };

        return canonical is not null;
    }

    public static Boolean TryGetHtmlTag(Utf8HtmlName name, out String canonical) =>
        TryGetHtmlTag(name.Verbatim, out canonical);

    private static String LookupHtmlTagLength1(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[0]) switch
        {
            (Byte)'a' => TagNames.A,
            (Byte)'b' => TagNames.B,
            (Byte)'i' => TagNames.I,
            (Byte)'p' => TagNames.P,
            (Byte)'q' => TagNames.Q,
            (Byte)'s' => TagNames.S,
            (Byte)'u' => TagNames.U,
            _ => null!,
        };

    private static String LookupHtmlTagLength2(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[1]) switch
        {
            (Byte)'1' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' ? TagNames.H1 : null!),
            (Byte)'2' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' ? TagNames.H2 : null!),
            (Byte)'3' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' ? TagNames.H3 : null!),
            (Byte)'4' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' ? TagNames.H4 : null!),
            (Byte)'5' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' ? TagNames.H5 : null!),
            (Byte)'6' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' ? TagNames.H6 : null!),
            (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'r' ? TagNames.Rb : null!),
            (Byte)'d' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'d' => TagNames.Dd,
                (Byte)'t' => TagNames.Td,
                _ => null!,
            },
            (Byte)'h' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'t' ? TagNames.Th : null!),
            (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'l' ? TagNames.Li : null!),
            (Byte)'l' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'d' => TagNames.Dl,
                (Byte)'o' => TagNames.Ol,
                (Byte)'u' => TagNames.Ul,
                _ => null!,
            },
            (Byte)'m' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'e' ? TagNames.Em : null!),
            (Byte)'p' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'r' ? TagNames.Rp : null!),
            (Byte)'r' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'b' => TagNames.Br,
                (Byte)'h' => TagNames.Hr,
                (Byte)'t' => TagNames.Tr,
                _ => null!,
            },
            (Byte)'t' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'d' => TagNames.Dt,
                (Byte)'r' => TagNames.Rt,
                (Byte)'t' => TagNames.Tt,
                _ => null!,
            },
            _ => null!,
        };

    private static String LookupHtmlTagLength3(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[2]) switch
        {
            (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'u' ? TagNames.Sub : null!),
            (Byte)'c' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'t' ? TagNames.Rtc : null!),
            (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'k' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'b' ? TagNames.Kbd : null!),
            (Byte)'e' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'r' ? TagNames.Pre : null!),
            (Byte)'g' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' ? TagNames.Big : null!),
                (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'m' ? TagNames.Img : null!),
                _ => null!,
            },
            (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'d' ? TagNames.Bdi : null!),
            (Byte)'l' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'c' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' ? TagNames.Col : null!),
                (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' ? TagNames.Del : null!),
                _ => null!,
            },
            (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'f' ? TagNames.Dfn : null!),
            (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'d' ? TagNames.Bdo : null!),
            (Byte)'p' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'m' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' ? TagNames.Map : null!),
                (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'u' ? TagNames.Sup : null!),
                (Byte)'x' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'m' ? TagNames.Xmp : null!),
                _ => null!,
            },
            (Byte)'r' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' ? TagNames.Dir : null!),
                (Byte)'v' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' ? TagNames.Var : null!),
                (Byte)'w' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'b' ? TagNames.Wbr : null!),
                _ => null!,
            },
            (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'n' ? TagNames.Ins : null!),
            (Byte)'v' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' ? TagNames.Div : null!),
                (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' ? TagNames.Nav : null!),
                _ => null!,
            },
            _ => null!,
        };

    private static String LookupHtmlTagLength4(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[0]) switch
        {
            (Byte)'a' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'r' ? TagNames.Abbr : null!),
                (Byte)'r' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' ? TagNames.Area : null!),
                _ => null!,
            },
            (Byte)'b' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'a' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' ? TagNames.Base : null!),
                (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'y' ? TagNames.Body : null!),
                _ => null!,
            },
            (Byte)'c' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' ? TagNames.Cite : null!),
                (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' ? TagNames.Code : null!),
                _ => null!,
            },
            (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' ? TagNames.Data : null!),
            (Byte)'f' => Utf8NameHash.ToLowerAscii(name[2]) switch
            {
                (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' ? TagNames.Font : null!),
                (Byte)'r' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'m' ? TagNames.Form : null!),
                _ => null!,
            },
            (Byte)'h' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'e' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'d' ? TagNames.Head : null!),
                (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'l' ? TagNames.Html : null!),
                _ => null!,
            },
            (Byte)'l' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'k' ? TagNames.Link : null!),
            (Byte)'m' => Utf8NameHash.ToLowerAscii(name[2]) switch
            {
                (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'n' ? TagNames.Main : null!),
                (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'u' ? TagNames.Menu : null!),
                (Byte)'r' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'k' ? TagNames.Mark : null!),
                (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' ? TagNames.Meta : null!),
                _ => null!,
            },
            (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'r' ? TagNames.NoBr : null!),
            (Byte)'r' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'y' ? TagNames.Ruby : null!),
            (Byte)'s' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'a' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'p' ? TagNames.Samp : null!),
                (Byte)'l' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' ? TagNames.Slot : null!),
                (Byte)'p' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'n' ? TagNames.Span : null!),
                _ => null!,
            },
            (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' ? TagNames.Time : null!),
            _ => null!,
        };

    private static String LookupHtmlTagLength5(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[1]) switch
        {
            (Byte)'a' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'l' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'l' ? TagNames.Label : null!),
                (Byte)'p' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'m' ? TagNames.Param : null!),
                (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Table : null!),
                _ => null!,
            },
            (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'y' ? TagNames.Tbody : null!),
            (Byte)'e' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'r' ? TagNames.Meter : null!),
            (Byte)'f' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'t' ? TagNames.Tfoot : null!),
            (Byte)'h' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'d' ? TagNames.Thead : null!),
            (Byte)'i' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Title : null!),
                (Byte)'v' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'o' ? TagNames.Video : null!),
                _ => null!,
            },
            (Byte)'m' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'e' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'d' ? TagNames.Embed : null!),
                (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Image : null!),
                (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'l' ? TagNames.Small : null!),
                _ => null!,
            },
            (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'t' ? TagNames.Input : null!),
            (Byte)'r' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'f' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Frame : null!),
                (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'k' ? TagNames.Track : null!),
                _ => null!,
            },
            (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Aside : null!),
            (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'y' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Style : null!),
            (Byte)'u' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'a' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'o' ? TagNames.Audio : null!),
                (Byte)'q' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' ? TagNames.Quote : null!),
                _ => null!,
            },
            _ => null!,
        };

    private static String LookupHtmlTagLength6(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[3]) switch
        {
            (Byte)'a' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'f' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' ? TagNames.Iframe : null!),
            (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'h' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'r' ? TagNames.Header : null!),
            (Byte)'e' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'l' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'d' ? TagNames.Legend : null!),
                (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'j' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' ? TagNames.Object : null!),
                (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' ? TagNames.Select : null!),
                _ => null!,
            },
            (Byte)'g' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'k' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'y' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'n' ? TagNames.Keygen : null!),
            (Byte)'i' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'c' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' ? TagNames.Script : null!),
                (Byte)'p' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'n' ? TagNames.Option : null!),
                (Byte)'t' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'k' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' ? TagNames.Strike : null!),
                _ => null!,
            },
            (Byte)'l' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'a' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' ? TagNames.Applet : null!),
                (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'g' ? TagNames.Dialog : null!),
                _ => null!,
            },
            (Byte)'o' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'h' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'p' ? TagNames.Hgroup : null!),
                (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'g' ? TagNames.Strong : null!),
                _ => null!,
            },
            (Byte)'p' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' ? TagNames.Output : null!),
            (Byte)'r' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' ? TagNames.Source : null!),
            (Byte)'t' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'n' ? TagNames.Button : null!),
                (Byte)'c' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'r' ? TagNames.Center : null!),
                (Byte)'f' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'r' ? TagNames.Footer : null!),
                _ => null!,
            },
            (Byte)'u' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'f' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' ? TagNames.Figure : null!),
            (Byte)'v' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'s' ? TagNames.Canvas : null!),
            _ => null!,
        };

    private static String LookupHtmlTagLength7(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[0]) switch
        {
            (Byte)'a' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'s' ? TagNames.Address : null!),
                (Byte)'r' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' ? TagNames.Article : null!),
                _ => null!,
            },
            (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'d' ? TagNames.Bgsound : null!),
            (Byte)'c' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'n' ? TagNames.Caption : null!),
            (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'s' ? TagNames.Details : null!),
            (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'x' ? TagNames.IsIndex : null!),
            (Byte)'l' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'g' ? TagNames.Listing : null!),
            (Byte)'m' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'q' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' ? TagNames.Marquee : null!),
            (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'d' ? TagNames.NoEmbed : null!),
            (Byte)'p' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' ? TagNames.Picture : null!),
            (Byte)'s' => Utf8NameHash.ToLowerAscii(name[1]) switch
            {
                (Byte)'e' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'n' ? TagNames.Section : null!),
                (Byte)'u' => (Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'y' ? TagNames.Summary : null!),
                _ => null!,
            },
            _ => null!,
        };

    private static String LookupHtmlTagLength8(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[2]) switch
        {
            (Byte)'a' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'f' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'t' ? TagNames.Frameset : null!),
            (Byte)'e' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'f' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'t' ? TagNames.Fieldset : null!),
            (Byte)'f' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'s' ? TagNames.NoFrames : null!),
            (Byte)'l' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'p' ? TagNames.Colgroup : null!),
            (Byte)'m' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'e' ? TagNames.Template : null!),
            (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'m' ? TagNames.MenuItem : null!),
            (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'s' ? TagNames.Progress : null!),
            (Byte)'s' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'f' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'t' ? TagNames.BaseFont : null!),
                (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'t' ? TagNames.NoScript : null!),
                _ => null!,
            },
            (Byte)'t' => Utf8NameHash.ToLowerAscii(name[0]) switch
            {
                (Byte)'d' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'t' ? TagNames.Datalist : null!),
                (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'p' ? TagNames.Optgroup : null!),
                _ => null!,
            },
            (Byte)'x' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'a' ? TagNames.Textarea : null!),
            _ => null!,
        };

    private static String LookupHtmlTagLength9(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'x' && Utf8NameHash.ToLowerAscii(name[8]) == (Byte)'t' ? TagNames.Plaintext : null!);

    private static String LookupHtmlTagLength10(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[0]) switch
        {
            (Byte)'b' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'k' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'q' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'u' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[8]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[9]) == (Byte)'e' ? TagNames.BlockQuote : null!),
            (Byte)'f' => (Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'p' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[8]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[9]) == (Byte)'n' ? TagNames.Figcaption : null!),
            _ => null!,
        };

    private static String LookupHtmlTagLength15(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[8]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[9]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[10]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[11]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[12]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[13]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[14]) == (Byte)'t' ? TagNames.SelectedContent : null!);

    public static Boolean TryGetMathMlTag(ReadOnlySpan<Byte> name, out String canonical)
    {
        canonical = name.Length switch
        {
            2 => LookupMathMlTagLength2(name),
            4 => LookupMathMlTagLength4(name),
            5 => LookupMathMlTagLength5(name),
            14 => LookupMathMlTagLength14(name),
            _ => null!,
        };

        return canonical is not null;
    }

    public static Boolean TryGetMathMlTag(Utf8HtmlName name, out String canonical) =>
        TryGetMathMlTag(name.Verbatim, out canonical);

    private static String LookupMathMlTagLength2(ReadOnlySpan<Byte> name) =>
        Utf8NameHash.ToLowerAscii(name[1]) switch
        {
            (Byte)'i' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' ? TagNames.Mi : null!),
            (Byte)'n' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' ? TagNames.Mn : null!),
            (Byte)'o' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' ? TagNames.Mo : null!),
            (Byte)'s' => (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' ? TagNames.Ms : null!),
            _ => null!,
        };

    private static String LookupMathMlTagLength4(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'h' ? TagNames.Math : null!);

    private static String LookupMathMlTagLength5(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'x' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'t' ? TagNames.Mtext : null!);

    private static String LookupMathMlTagLength14(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'a' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'t' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[8]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[9]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[10]) == (Byte)'-' && Utf8NameHash.ToLowerAscii(name[11]) == (Byte)'x' && Utf8NameHash.ToLowerAscii(name[12]) == (Byte)'m' && Utf8NameHash.ToLowerAscii(name[13]) == (Byte)'l' ? TagNames.AnnotationXml : null!);

    public static Boolean TryGetSvgTag(ReadOnlySpan<Byte> name, out String canonical)
    {
        canonical = name.Length switch
        {
            3 => LookupSvgTagLength3(name),
            4 => LookupSvgTagLength4(name),
            6 => LookupSvgTagLength6(name),
            13 => LookupSvgTagLength13(name),
            _ => null!,
        };

        return canonical is not null;
    }

    public static Boolean TryGetSvgTag(Utf8HtmlName name, out String canonical) =>
        TryGetSvgTag(name.Verbatim, out canonical);

    private static String LookupSvgTagLength3(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'v' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'g' ? TagNames.Svg : null!);

    private static String LookupSvgTagLength4(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'d' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'s' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'c' ? TagNames.Desc : null!);

    private static String LookupSvgTagLength6(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'l' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'e' ? TagNames.Circle : null!);

    private static String LookupSvgTagLength13(ReadOnlySpan<Byte> name) =>
        (Utf8NameHash.ToLowerAscii(name[0]) == (Byte)'f' && Utf8NameHash.ToLowerAscii(name[1]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[2]) == (Byte)'r' && Utf8NameHash.ToLowerAscii(name[3]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[4]) == (Byte)'i' && Utf8NameHash.ToLowerAscii(name[5]) == (Byte)'g' && Utf8NameHash.ToLowerAscii(name[6]) == (Byte)'n' && Utf8NameHash.ToLowerAscii(name[7]) == (Byte)'o' && Utf8NameHash.ToLowerAscii(name[8]) == (Byte)'b' && Utf8NameHash.ToLowerAscii(name[9]) == (Byte)'j' && Utf8NameHash.ToLowerAscii(name[10]) == (Byte)'e' && Utf8NameHash.ToLowerAscii(name[11]) == (Byte)'c' && Utf8NameHash.ToLowerAscii(name[12]) == (Byte)'t' ? TagNames.ForeignObject : null!);

}
