//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleInteraction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stylesheets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stylesheets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleInteraction.Stylesheets", typeof(Stylesheets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Allgemeines*/
        ///* { margin: 0; padding: 0; }
        ///img { border: 0; }
        ///form { margin: 0; }
        ///header, nav, article, footer, section, aside { display: block; }
        ///input[type=&quot;search&quot;] { -webkit-appearance: textfield; }
        ///
        ///html, body
        ///{
        ///	min-height: 100%;
        ///	color: #000000;
        ///	font-family: Calibri, Tahoma, Arial, Sans-Serif;
        ///	font-size: 10pt;
        ///	background-color: #F8F8F8;
        ///	text-align: justify;
        ///}
        ///
        ///a
        ///{
        ///	text-decoration: underline;
        ///	color: #333333;
        ///}
        ///
        ///a:hover
        ///{
        ///	text-decoration: none;
        ///}
        ///
        ///hr
        ///{
        ///	border: no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rsi {
            get {
                return ResourceManager.GetString("rsi", resourceCulture);
            }
        }
    }
}
