<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net8.0;net10.0</TargetFrameworks>
    <SignAssembly>false</SignAssembly>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AngleSharp\AngleSharp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="CsQuery" Condition=" '$(TargetFramework)' == 'net472' " />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <None Update="page.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>