<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net8.0;net10.0</TargetFrameworks>
    <SignAssembly Condition="'$(TargetFramework)' != 'net10.0'">false</SignAssembly>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AngleSharp\AngleSharp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.8" />
    <PackageReference Include="CsQuery" Version="1.3.5-beta5" Condition=" '$(TargetFramework)' == 'net472' " />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.7" Condition=" '$(TargetFramework)' == 'net10.0' " />
  </ItemGroup>

  <ItemGroup>
    <None Update="page.html" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\AngleSharp.Core.Tests\Pages\nbc.html" Link="nbc.html" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\AngleSharp.Core.Tests\Resources\utf8_edu.bin" Link="utf8_edu.bin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
