using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using AngleSharp.Html.Parser.Utf8;

var root = FindRepositoryRoot(args.Length == 0 ? Environment.CurrentDirectory : args[0]);
var input = Path.Combine(root, "src", "AngleSharp", "Dom", "TagNames.cs");
var output = Path.Combine(
    root,
    "src",
    "AngleSharp",
    "Html",
    "Parser",
    "Utf8",
    "Utf8CanonicalNameProvider.Generated.cs"
);

var regions = ReadRegions(input);
var source = new StringBuilder(
    """
    // <auto-generated />
    using System;
    using AngleSharp.Dom;

    namespace AngleSharp.Html.Parser.Utf8;

    internal static partial class Utf8CanonicalNameProvider
    {

    """
);

AppendLookup(source, "Html", regions["HTML Tags"]);
AppendLookup(source, "MathMl", regions["MathML Tags"]);
AppendLookup(source, "Svg", regions["SVG Tags"]);
source.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(output)!);
File.WriteAllText(output, source.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated {output}");

static Dictionary<string, List<Entry>> ReadRegions(string path)
{
    var result = new Dictionary<string, List<Entry>>(StringComparer.Ordinal);
    var field = new Regex("public static readonly String (?<field>\\w+) = \"(?<value>[^\"]+)\";");
    string? region = null;
    foreach (var line in File.ReadLines(path))
    {
        var trimmed = line.Trim();
        if (trimmed.StartsWith("#region ", StringComparison.Ordinal))
        {
            region = trimmed[8..];
            result.TryAdd(region, []);
            continue;
        }
        if (trimmed == "#endregion")
        {
            region = null;
            continue;
        }
        if (region is null)
        {
            continue;
        }

        var match = field.Match(line);
        if (!match.Success)
        {
            continue;
        }
        var value = match.Groups["value"].Value;
        if (value.Any(static character => character > 0x7F))
        {
            throw new InvalidOperationException($"TagNames.{match.Groups["field"].Value} is not ASCII.");
        }
        result[region].Add(
            new Entry(
                match.Groups["field"].Value,
                value,
                Utf8NameHash.ComputeSemantic(Encoding.ASCII.GetBytes(value))
            )
        );
    }
    return result;
}

static void AppendLookup(StringBuilder source, string category, List<Entry> entries)
{
    ValidateKeys(category, entries);

    source.AppendLine($"    public static Boolean TryGet{category}Tag(ReadOnlySpan<Byte> name, out String canonical)");
    source.AppendLine("    {");
    source.AppendLine("        canonical = name.Length switch");
    source.AppendLine("        {");
    foreach (var group in entries.GroupBy(static entry => entry.Value.Length).OrderBy(static group => group.Key))
    {
        source.AppendLine($"            {group.Key} => Lookup{category}TagLength{group.Key}(name),");
    }
    source.AppendLine("            _ => null!,");
    source.AppendLine("        };");
    source.AppendLine();
    source.AppendLine("        return canonical is not null;");
    source.AppendLine("    }");
    source.AppendLine();
    source.AppendLine($"    public static Boolean TryGet{category}Tag(Utf8HtmlName name, out String canonical) =>");
    source.AppendLine($"        TryGet{category}Tag(name.Verbatim, out canonical);");
    source.AppendLine();

    foreach (var group in entries.GroupBy(static entry => entry.Value.Length).OrderBy(static group => group.Key))
    {
        source.AppendLine($"    private static String Lookup{category}TagLength{group.Key}(ReadOnlySpan<Byte> name) =>");
        AppendDecision(source, group.ToList(), [], "        ", inline: false);
        source.AppendLine(";");
        source.AppendLine();
    }
}

static void AppendDecision(
    StringBuilder source,
    List<Entry> entries,
    HashSet<int> tested,
    string indent,
    bool inline
)
{
    if (entries.Count == 1)
    {
        var entry = entries[0];
        if (!inline)
        {
            source.Append(indent);
        }
        var remaining = Enumerable
            .Range(0, entry.Value.Length)
            .Where(position => !tested.Contains(position))
            .ToArray();
        if (remaining.Length == 0)
        {
            source.Append($"TagNames.{entry.Field}");
            return;
        }
        source.Append('(');
        for (var index = 0; index < remaining.Length; index++)
        {
            if (index != 0)
            {
                source.Append(" && ");
            }
            var leafPosition = remaining[index];
            source.Append(
                $"Utf8NameHash.ToLowerAscii(name[{leafPosition}]) == (Byte){FormatByte(ToLowerAscii((Byte)entry.Value[leafPosition]))}"
            );
        }
        source.Append($" ? TagNames.{entry.Field} : null!)");
        return;
    }

    var position = ChoosePosition(entries, tested);
    if (position < 0)
    {
        throw new InvalidOperationException(
            "The byte decision tree cannot distinguish: "
                + String.Join(", ", entries.Select(static entry => entry.Value))
        );
    }

    var nextTested = new HashSet<int>(tested) { position };
    if (!inline)
    {
        source.Append(indent);
    }
    source.AppendLine($"Utf8NameHash.ToLowerAscii(name[{position}]) switch");
    source.AppendLine(indent + "{");
    foreach (var group in entries
        .GroupBy(entry => ToLowerAscii((byte)entry.Value[position]))
        .OrderBy(static group => group.Key))
    {
        source.Append($"{indent}    (Byte){FormatByte(group.Key)} => ");
        AppendDecision(source, group.ToList(), nextTested, indent + "    ", inline: true);
        source.AppendLine(",");
    }
    source.AppendLine(indent + "    _ => null!,");
    source.Append(indent + "}");
}

static int ChoosePosition(List<Entry> entries, HashSet<int> tested)
{
    var bestPosition = -1;
    var bestDistinct = 1;
    var bestLargestBucket = Int32.MaxValue;
    for (var position = 0; position < entries[0].Value.Length; position++)
    {
        if (tested.Contains(position))
        {
            continue;
        }
        var groups = entries
            .GroupBy(entry => ToLowerAscii((byte)entry.Value[position]))
            .Select(static group => group.Count())
            .ToArray();
        if (
            groups.Length > bestDistinct
            || groups.Length == bestDistinct && groups.Max() < bestLargestBucket
        )
        {
            bestPosition = position;
            bestDistinct = groups.Length;
            bestLargestBucket = groups.Max();
        }
    }
    return bestPosition;
}

static void ValidateKeys(string category, List<Entry> entries)
{
    var duplicate = entries
        .GroupBy(static entry => (entry.Value.Length, entry.Hash))
        .FirstOrDefault(static group => group.Count() != 1);
    if (duplicate is not null)
    {
        throw new InvalidOperationException(
            $"Duplicate {category} canonical-name key ({duplicate.Key.Length}, 0x{duplicate.Key.Hash:X16}): "
                + String.Join(", ", duplicate.Select(static entry => entry.Value))
        );
    }
}

static string FormatByte(byte value) => value switch
{
    (byte)'\\' => "'\\\\'",
    (byte)'\'' => "'\\\''",
    >= 0x20 and <= 0x7E => $"'{(char)value}'",
    _ => $"0x{value:X2}",
};

static byte ToLowerAscii(byte value) =>
    (uint)(value - (byte)'A') <= 'Z' - 'A' ? (byte)(value | 0x20) : value;

static string FindRepositoryRoot(string start)
{
    var directory = new DirectoryInfo(Path.GetFullPath(start));
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "src", "AngleSharp", "Dom", "TagNames.cs")))
        {
            return directory.FullName;
        }
        directory = directory.Parent;
    }
    throw new DirectoryNotFoundException("Could not locate the AngleSharp repository root.");
}

internal sealed record Entry(string Field, string Value, ulong Hash);
