//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleInteraction.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleInteraction.Assets.HtmlFiles", typeof(HtmlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Application Auto-update via Online Files in C# - CodeProject&lt;/title&gt; 
        ///	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;http://s.codeproject.com/App_Themes/Std/Css/Main.min.css?dt=2.6.130329.1&quot;&gt;
        ///&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;http://s.codeproject.com/App_Themes/Easter/Css/Main.min.css?dt=2.6.130329.1&quot;&gt;
        ///
        ///	
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeProject {
            get {
                return ResourceManager.GetString("CodeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;&lt;html &gt;&lt;head&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8,IE=9&quot; /&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;&lt;meta name=&quot;description&quot; content=&quot;Ausführliche und aktuelle Beiträge - von Google News aus verschiedenen Nachrichtenquellen aus aller Welt zusammengetragen&quot;/&gt;&lt;title&gt;Google News&lt;/title&gt;&lt;link href=&quot;http://www.gstatic.com/news-static/img/favicon.ico&quot; rel=&quot;icon&quot; type=&quot;image/x-icon&quot;/&gt;&lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; href=&quot;http://news.google.de/ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleNews {
            get {
                return ResourceManager.GetString("GoogleNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Frameset//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Simon Mages&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;frameset rows=&quot;*,18&quot; border=&quot;0&quot;&gt;
        ///    &lt;frameset rows=&quot;110,*&quot; border=&quot;0&quot;&gt;
        ///        &lt;frame src=&quot;head.html&quot; /&gt;
        ///        &lt;frameset cols=&quot;25%,*&quot; border=&quot;0&quot;&gt;
        ///            &lt;frame src=&quot;navigation.html&quot; /&gt;
        ///            &lt;frame name=&quot;start&quot; src=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simon {
            get {
                return ResourceManager.GetString("Simon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;meta charset=utf-8&gt;
        ///&lt;title&gt;Ein Beispiel&lt;/title&gt;
        ///&lt;div&gt;
        ///Ein Test...
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
        ///	&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot; debug=&quot;true&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;	
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///	
        ///	  &lt;div class=&quot;head&quot;&gt;
        ///   &lt;p&gt;&lt;a href=&quot;http://www.w3.org/&quot;&gt;&lt;img height=48 alt=W3C src=&quot;http://www.w3.org/Icons/w3c_home&quot; width=72&gt;&lt;/a&gt;
        ///
        ///   &lt;h1 id=&quot;title&quot;&gt;Selectors&lt;/h1&gt;
        ///
        ///   &lt;h2&gt;W3C Working Draft 15 December 200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string W3C {
            get {
                return ResourceManager.GetString("W3C", resourceCulture);
            }
        }
    }
}
