//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;catalog&gt;
        ///   &lt;book id=&quot;bk101&quot;&gt;
        ///      &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///      &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///      &lt;genre&gt;Computer&lt;/genre&gt;
        ///      &lt;price&gt;44.95&lt;/price&gt;
        ///      &lt;publish_date&gt;2000-10-01&lt;/publish_date&gt;
        ///      &lt;description&gt;An in-depth look at creating applications 
        ///      with XML.&lt;/description&gt;
        ///   &lt;/book&gt;
        ///   &lt;book id=&quot;bk102&quot;&gt;
        ///      &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///      &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///      &lt;genre&gt;Fantasy&lt;/genre&gt;
        ///      &lt;price&gt;5.95&lt;/price&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Asserts {
            get {
                return ResourceManager.GetString("Asserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;catalog&gt;
        ///   &lt;book id=&quot;bk101&quot;&gt;
        ///      &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///      &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///      &lt;genre&gt;Computer&lt;/genre&gt;
        ///      &lt;price&gt;44.95&lt;/price&gt;
        ///      &lt;publish_date&gt;2000-10-01&lt;/publish_date&gt;
        ///      &lt;description&gt;An in-depth look at creating applications 
        ///      with XML.&lt;/description&gt;
        ///   &lt;/book&gt;
        ///   &lt;book id=&quot;bk102&quot;&gt;
        ///      &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///      &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///      &lt;genre&gt;Fantasy&lt;/genre&gt;
        ///      &lt;price&gt;5.95&lt;/price&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;!-- Edited by XMLSpy® --&gt;
        ///&lt;breakfast_menu&gt;
        ///	&lt;food&gt;
        ///		&lt;name&gt;Belgian Waffles&lt;/name&gt;
        ///		&lt;price&gt;$5.95&lt;/price&gt;
        ///		&lt;description&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;/description&gt;
        ///		&lt;calories&gt;650&lt;/calories&gt;
        ///	&lt;/food&gt;
        ///	&lt;food&gt;
        ///		&lt;name&gt;Strawberry Belgian Waffles&lt;/name&gt;
        ///		&lt;price&gt;$7.95&lt;/price&gt;
        ///		&lt;description&gt;Light Belgian waffles covered with strawberries and whipped cream&lt;/description&gt;
        ///		&lt;calories&gt;900&lt;/calories&gt;
        ///	&lt;/food&gt;
        ///	&lt;food&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FoodMenu {
            get {
                return ResourceManager.GetString("FoodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--inform the XML processor
        ///  that an external DTD is referenced--&gt;
        ///&lt;?xml version=&quot;1.0&quot; standalone=&quot;no&quot; ?&gt;
        ///
        ///&lt;!--define the location of the
        ///  external DTD using a relative URL address--&gt;
        ///&lt;!DOCTYPE document SYSTEM &quot;subjects.dtd&quot;&gt;
        ///
        ///&lt;document&gt;
        ///  &lt;title&gt;Subjects available in Mechanical Engineering.&lt;/title&gt;
        ///  &lt;subjectID&gt;2.303&lt;/subjectID&gt;
        ///    &lt;subjectname&gt;Fluid Mechanics&lt;/subjectname&gt;
        ///    &lt;prerequisite&gt;
        ///      &lt;subjectID&gt;1.001&lt;/subjectID&gt;
        ///      &lt;subjectname&gt;Mathematics&lt;/subjectname&gt;
        ///    &lt;/prerequisi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MechanicalEngineering {
            get {
                return ResourceManager.GetString("MechanicalEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p id=&quot;test&quot; class=&quot;testClass&quot;&gt;Test &lt;code&gt;&amp;lt;p&amp;gt;&lt;/code&gt; with &lt;code&gt;id=&quot;test&quot;&lt;/code&gt; and &lt;code&gt;class=&quot;testClass&quot;&lt;/code&gt;. It contains a
        ///&lt;b id=&quot;testB&quot;&gt;&lt;code&gt;&amp;lt;b&amp;gt;&lt;/code&gt; with id=&quot;testB&quot;&lt;/b&gt;.&lt;/p&gt;
        ///
        ///&lt;p id=&quot;test2&quot; class=&quot;nonsense testClass&quot;&gt;&lt;code&gt;&amp;lt;p&amp;gt;&lt;/code&gt; with id=&quot;test2&quot; and class=&quot;nonsense testClass&quot;&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;ppk&gt;This is a &lt;code&gt;&amp;lt;ppk&amp;gt;&lt;/code&gt; tag.&lt;/ppk&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;This &lt;code&gt;&amp;lt;img&amp;gt;&lt;/code&gt;has &lt;code&gt;name&lt;/code&gt; (and not &lt;code&gt;id&lt;/code&gt;!) test3
        ///&lt;img src=&quot;../../browsers/pix/logo_op3.gif&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuirksMode {
            get {
                return ResourceManager.GetString("QuirksMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///&lt;body id=&quot;theBody&quot;&gt;
        ///	&lt;div id=&quot;myDiv&quot;&gt;
        ///		&lt;div id=&quot;someOtherDiv&quot;&gt;subdiv!&lt;/div&gt;
        ///		&lt;p&gt;&lt;a href=&quot;http://www.google.com&quot;&gt;hi&lt;/a&gt;&lt;span class=&quot;hyphen-separated&quot;&gt;test&lt;/span&gt;&lt;span&gt;oh&lt;/span&gt;&lt;/p&gt;
        ///	&lt;/div&gt;
        ///	&lt;p class=&quot;hiclass&quot;&gt;hi!!&lt;/p&gt;
        ///	&lt;div class=&quot;checkit&quot;&gt;wooo&lt;p class=&quot;omg ohyeah&quot;&gt;eeeee&lt;/p&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;checkit&quot;&gt;woootooo&lt;a href=&quot;http://colinramsay.co.uk/&quot;&gt;we&lt;/a&gt;&lt;/div&gt;
        ///	&lt;form&gt;
        ///		&lt;input /&gt;
        ///	&lt;/form&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SelectorsWebpage {
            get {
                return ResourceManager.GetString("SelectorsWebpage", resourceCulture);
            }
        }
    }
}
