//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///&lt;body id=&quot;theBody&quot;&gt;
        ///	&lt;div id=&quot;myDiv&quot;&gt;
        ///		&lt;div id=&quot;someOtherDiv&quot;&gt;subdiv!&lt;/div&gt;
        ///		&lt;p&gt;&lt;a href=&quot;http://www.google.com&quot;&gt;hi&lt;/a&gt;&lt;span class=&quot;hyphen-separated&quot;&gt;test&lt;/span&gt;&lt;span&gt;oh&lt;/span&gt;&lt;/p&gt;
        ///	&lt;/div&gt;
        ///	&lt;p class=&quot;hiclass&quot;&gt;hi!!&lt;/p&gt;
        ///	&lt;div class=&quot;checkit&quot;&gt;wooo&lt;p class=&quot;omg ohyeah&quot;&gt;eeeee&lt;/p&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;checkit&quot;&gt;woootooo&lt;a href=&quot;http://colinramsay.co.uk/&quot;&gt;we&lt;/a&gt;&lt;/div&gt;
        ///	&lt;form&gt;
        ///		&lt;input /&gt;
        ///	&lt;/form&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SelectorsWebpage {
            get {
                return ResourceManager.GetString("SelectorsWebpage", resourceCulture);
            }
        }
    }
}
