namespace AngleSharp.Html
{
    using AngleSharp.Dom;
    using AngleSharp.Html.Dom;
    using AngleSharp.Text;
    using System;

    /// <summary>
    /// Provides string to HTMLElement instance creation mappings.
    /// </summary>
    sealed class HtmlElementFactory : IElementFactory<Document, HtmlElement>
    {
        /// <summary>
        /// Returns a specialized HTMLElement instance for the given tag name.
        /// </summary>
        /// <param name="document">The document that owns the element.</param>
        /// <param name="localName">The given tag name.</param>
        /// <param name="prefix">The prefix of the element, if any.</param>
        /// <param name="flags">The optional flags, if any.</param>
        /// <returns>The specialized HTMLElement instance.</returns>
        public HtmlElement Create(Document document, String localName, String? prefix = null, NodeFlags flags = NodeFlags.None)
        {
            // NOTE: When adding cases where the constant in TagNames is mixed-case, make sure to add a mixed-case pattern matching case, e.g.:
            // var tagName when tagName.Equals(TagNames._MixedCaseConstant, StringComparison.OrdinalIgnoreCase) => ...
            return localName.ToLowerInvariant() switch
            {
                TagNames._Div => new HtmlDivElement(document, prefix),
                TagNames._A => new HtmlAnchorElement(document, prefix),
                TagNames._Img => new HtmlImageElement(document, prefix),
                TagNames._P => new HtmlParagraphElement(document, prefix),
                TagNames._Br => new HtmlBreakRowElement(document, prefix),
                TagNames._Input => new HtmlInputElement(document, prefix),
                TagNames._Button => new HtmlButtonElement(document, prefix),
                TagNames._Textarea => new HtmlTextAreaElement(document, prefix),
                TagNames._Li => new HtmlListItemElement(document, TagNames._Li, prefix),
                TagNames._H1 => new HtmlHeadingElement(document, TagNames._H1, prefix),
                TagNames._H2 => new HtmlHeadingElement(document, TagNames._H2, prefix),
                TagNames._H3 => new HtmlHeadingElement(document, TagNames._H3, prefix),
                TagNames._H4 => new HtmlHeadingElement(document, TagNames._H4, prefix),
                TagNames._H5 => new HtmlHeadingElement(document, TagNames._H5, prefix),
                TagNames._H6 => new HtmlHeadingElement(document, TagNames._H6, prefix),
                TagNames._Ul => new HtmlUnorderedListElement(document, prefix),
                TagNames._Ol => new HtmlOrderedListElement(document, prefix),
                TagNames._Dl => new HtmlDefinitionListElement(document, prefix),
                TagNames._Link => new HtmlLinkElement(document, prefix),
                TagNames._Meta => new HtmlMetaElement(document, prefix),
                TagNames._Label => new HtmlLabelElement(document, prefix),
                TagNames._Fieldset => new HtmlFieldSetElement(document, prefix),
                TagNames._Legend => new HtmlLegendElement(document, prefix),
                TagNames._Form => new HtmlFormElement(document, prefix),
                TagNames._Select => new HtmlSelectElement(document, prefix),
                TagNames._Pre => new HtmlPreElement(document, prefix),
                TagNames._Hr => new HtmlHrElement(document, prefix),
                TagNames._Dir => new HtmlDirectoryElement(document, prefix),
                TagNames._Font => new HtmlFontElement(document, prefix),
                TagNames._Param => new HtmlParamElement(document, prefix),
                TagNames._BlockQuote => new HtmlQuoteElement(document, TagNames._BlockQuote, prefix),
                TagNames._Quote => new HtmlQuoteElement(document, TagNames._Quote, prefix),
                TagNames._Q => new HtmlQuoteElement(document, TagNames._Q, prefix),
                TagNames._Canvas => new HtmlCanvasElement(document, prefix),
                TagNames._Caption => new HtmlTableCaptionElement(document, prefix),
                TagNames._Td => new HtmlTableDataCellElement(document, prefix),
                TagNames._Tr => new HtmlTableRowElement(document, prefix),
                TagNames._Table => new HtmlTableElement(document, prefix),
                TagNames._Tbody => new HtmlTableSectionElement(document, TagNames._Tbody, prefix),
                TagNames._Th => new HtmlTableHeaderCellElement(document, prefix),
                TagNames._Tfoot => new HtmlTableSectionElement(document, TagNames._Tfoot, prefix),
                TagNames._Thead => new HtmlTableSectionElement(document, TagNames._Thead, prefix),
                TagNames._Colgroup => new HtmlTableColgroupElement(document, prefix),
                TagNames._Col => new HtmlTableColElement(document, prefix),
                TagNames._Del => new HtmlModElement(document, TagNames._Del, prefix),
                TagNames._Ins => new HtmlModElement(document, TagNames._Ins, prefix),
                TagNames._Applet => new HtmlAppletElement(document, prefix),
                TagNames._Object => new HtmlObjectElement(document, prefix),
                TagNames._Optgroup => new HtmlOptionsGroupElement(document, prefix),
                TagNames._Option => new HtmlOptionElement(document, prefix),
                TagNames._Style => new HtmlStyleElement(document, prefix),
                TagNames._Script => new HtmlScriptElement(document, prefix),
                TagNames._Iframe => new HtmlIFrameElement(document, prefix),
                TagNames._Dd => new HtmlListItemElement(document, TagNames._Dd, prefix),
                TagNames._Dt => new HtmlListItemElement(document, TagNames._Dt, prefix),
                TagNames._Frameset => new HtmlFrameSetElement(document, prefix),
                TagNames._Frame => new HtmlFrameElement(document, prefix),
                TagNames._Audio => new HtmlAudioElement(document, prefix),
                TagNames._Video => new HtmlVideoElement(document, prefix),
                TagNames._Span => new HtmlSpanElement(document, prefix),
                TagNames._Dialog => new HtmlDialogElement(document, prefix),
                TagNames._Details => new HtmlDetailsElement(document, prefix),
                TagNames._Source => new HtmlSourceElement(document, prefix),
                TagNames._Track => new HtmlTrackElement(document, prefix),
                TagNames._Wbr => new HtmlWbrElement(document, prefix),
                TagNames._B => new HtmlBoldElement(document, prefix),
                TagNames._Big => new HtmlBigElement(document, prefix),
                TagNames._Strike => new HtmlStrikeElement(document, prefix),
                TagNames._Code => new HtmlCodeElement(document, prefix),
                TagNames._Em => new HtmlEmphasizeElement(document, prefix),
                TagNames._I => new HtmlItalicElement(document, prefix),
                TagNames._S => new HtmlStruckElement(document, prefix),
                TagNames._Small => new HtmlSmallElement(document, prefix),
                TagNames._Strong => new HtmlStrongElement(document, prefix),
                TagNames._U => new HtmlUnderlineElement(document, prefix),
                TagNames._Tt => new HtmlTeletypeTextElement(document, prefix),
                TagNames._Address => new HtmlAddressElement(document, prefix),
                TagNames._Main => new HtmlSemanticElement(document, TagNames._Main, prefix),
                TagNames._Summary => new HtmlSemanticElement(document, TagNames._Summary, prefix),
                TagNames._Center => new HtmlSemanticElement(document, TagNames._Center, prefix),
                TagNames._Listing => new HtmlSemanticElement(document, TagNames._Listing, prefix),
                TagNames._Nav => new HtmlSemanticElement(document, TagNames._Nav, prefix),
                TagNames._Article => new HtmlSemanticElement(document, TagNames._Article, prefix),
                TagNames._Aside => new HtmlSemanticElement(document, TagNames._Aside, prefix),
                TagNames._Figcaption => new HtmlSemanticElement(document, TagNames._Figcaption, prefix),
                TagNames._Figure => new HtmlSemanticElement(document, TagNames._Figure, prefix),
                TagNames._Section => new HtmlSemanticElement(document, TagNames._Section, prefix),
                TagNames._Footer => new HtmlSemanticElement(document, TagNames._Footer, prefix),
                TagNames._Header => new HtmlSemanticElement(document, TagNames._Header, prefix),
                TagNames._Hgroup => new HtmlSemanticElement(document, TagNames._Hgroup, prefix),
                TagNames._Cite => new HtmlElement(document, TagNames._Cite, prefix),
                TagNames._Ruby => new HtmlRubyElement(document, prefix),
                TagNames._Rt => new HtmlRtElement(document, prefix),
                TagNames._Rp => new HtmlRpElement(document, prefix),
                TagNames._Rtc => new HtmlRtcElement(document, prefix),
                TagNames._Rb => new HtmlRbElement(document, prefix),
                TagNames._Map => new HtmlMapElement(document, prefix),
                TagNames._Datalist => new HtmlDataListElement(document, prefix),
                TagNames._Xmp => new HtmlXmpElement(document, prefix),
                TagNames._Picture => new HtmlPictureElement(document, prefix),
                TagNames._Template => new HtmlTemplateElement(document, prefix),
                TagNames._Time => new HtmlTimeElement(document, prefix),
                TagNames._Progress => new HtmlProgressElement(document, prefix),
                TagNames._Meter => new HtmlMeterElement(document, prefix),
                TagNames._Output => new HtmlOutputElement(document, prefix),
                TagNames._Keygen => new HtmlKeygenElement(document, prefix),
                TagNames._Title => new HtmlTitleElement(document, prefix),
                TagNames._Head => new HtmlHeadElement(document, prefix),
                TagNames._Body => new HtmlBodyElement(document, prefix),
                TagNames._Html => new HtmlHtmlElement(document, prefix),
                TagNames._Area => new HtmlAreaElement(document, prefix),
                TagNames._Embed => new HtmlEmbedElement(document, prefix),
                TagNames._MenuItem => new HtmlMenuItemElement(document, prefix),
                TagNames._Slot => new HtmlSlotElement(document, prefix),
                TagNames._NoScript => new HtmlNoScriptElement(document, prefix),
                TagNames._NoEmbed => new HtmlNoEmbedElement(document, prefix),
                TagNames._NoFrames => new HtmlNoFramesElement(document, prefix),
                TagNames._NoBr => new HtmlNoNewlineElement(document, prefix),
                TagNames._Menu => new HtmlMenuElement(document, prefix),
                TagNames._Base => new HtmlBaseElement(document, prefix),
                TagNames._BaseFont => new HtmlBaseFontElement(document, prefix),
                TagNames._Bgsound => new HtmlBgsoundElement(document, prefix),
                TagNames._Marquee => new HtmlMarqueeElement(document, prefix),
                TagNames._Data => new HtmlDataElement(document, prefix),
                TagNames._Plaintext => new HtmlSemanticElement(document, TagNames._Plaintext, prefix),
                TagNames._IsIndex => new HtmlIsIndexElement(document, prefix),
                TagNames._Mark => new HtmlElement(document, TagNames._Mark),
                TagNames._Sub => new HtmlElement(document, TagNames._Sub),
                TagNames._Sup => new HtmlElement(document, TagNames._Sup),
                TagNames._Dfn => new HtmlElement(document, TagNames._Dfn),
                TagNames._Kbd => new HtmlElement(document, TagNames._Kbd),
                TagNames._Var => new HtmlElement(document, TagNames._Var),
                TagNames._Samp => new HtmlElement(document, TagNames._Samp),
                TagNames._Abbr => new HtmlElement(document, TagNames._Abbr),
                TagNames._Bdi => new HtmlElement(document, TagNames._Bdi),
                TagNames._Bdo => new HtmlElement(document, TagNames._Bdo),
                _ => new HtmlUnknownElement(document, localName.HtmlLower(), prefix, flags)
            };
        }
    }
}