//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngleSharp.Performance.Selector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Page {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Page() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AngleSharp.Performance.Selector.Page", typeof(Page).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;head&quot;&gt;
        ///   &lt;p&gt;&lt;a href=&quot;http://www.w3.org/&quot;&gt;&lt;img height=48 alt=W3C src=&quot;http://www.w3.org/Icons/w3c_home&quot; width=72&gt;&lt;/a&gt;
        ///
        ///   &lt;h1 id=&quot;title&quot;&gt;Selectors&lt;/h1&gt;
        ///
        ///   &lt;h2&gt;W3C Working Draft 15 December 2005&lt;/h2&gt;
        ///
        ///   &lt;dl&gt;
        ///
        ///    &lt;dt&gt;This version:
        ///
        ///    &lt;dd&gt;&lt;a href=&quot;http://www.w3.org/TR/2005/WD-css3-selectors-20051215&quot;&gt;
        ///                 http://www.w3.org/TR/2005/WD-css3-selectors-20051215&lt;/a&gt;
        ///
        ///    &lt;dt&gt;Latest version:
        ///
        ///    &lt;dd&gt;&lt;a href=&quot;http://www.w3.org/TR/css3-selectors&quot;&gt;
        ///                 http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
    }
}
